### ISSUE TITLE
Error: Docker build failed with exit code 1

### ISSUE THREAD

**Issue by carbscountry** [kuromt/diff-notebooks#6]
以下のworkflowを走らせるとDocker buildでexit 1になってしまいます、、
```
# https://github.com/marketplace/actions/diff-notebooks
name: nbdiff-web-exporter
on: [pull_request]

jobs:
  diff-action-test:
    runs-on: ubuntu-latest
    name: diff notebooks
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: diff notebooks
        uses: kuromt/diff-notebooks@v0.0.1
        id: nbdiff-web-exporter-action
        with:
          remote: "origin/diff-notebooks"
          export_dir: "./artifacts"
      - uses: actions/upload-artifact@v3
        with:
          name: diff-notebooks
          path: ${{steps.nbdiff-web-exporter-action.outputs.export_dir}}

```
